#!/bin/bash
wget -O /www/xderm/xderm-mini https://raw.githubusercontent.com/andigoenfx/xderm-gui-version/main//v2.9/xderm-mini -q
wget -O /www/xderm/index.php https://raw.githubusercontent.com/andigoenfx/xderm-gui-version/main//v2.9/index.php -q
